name: github pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v5
      
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: src/package-lock.json
      
      # Install dependencies
      - name: Install dependencies
        run: |
          cd src
          npm install
      
      # Build Tailwind CSS (minified)
      - name: Build CSS
        run: |
          cd src
          npm run build
      
      # Copy files to dist folder
      - name: Copy files to dist folder
        run: |
          cp src/index.html dist/
          cp src/app.css dist/
          cp src/data.json dist/
          cp -r src/images dist/
      
      # Commit to gh-pages
      - name: Commit dist to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
